### ISSUE TITLE
Cannot customize wording inside tours_for_item

### ISSUE THREAD

**Issue by cheshirecatnyc** [CPHDH/TourBuilder#5]
The Curatescape theme appearance settings allow you to provide Custom Labels, where "Tour" and "Tours" can be changed.

But inside the tours_for_item function (TourFunctions.php), it seems to be hard-coded.  I see you can pass in a heading, but that's not going to be adjusted to singular/plural based on the number of related tours.

> $h=(count($results)>1) ? __('Related Tours') : __('Related Tour');

This fix is not urgent

**Comment by ebellempire** [comment]
Addressed with theme update: https://github.com/CPHDH/theme-curatescape/commit/f6955ee5accee30f0d0bf6fb4850c362ce5f6a6b

The fix uses plural by default, similar to the "Tags" and "Subjects" lists, which also don't count first. A future update may move the actual functionality into the theme (see `tours_for_item()` in `TourBuilder/Tourfunctions.php`) to allow for plural/singular differentiation.
